name = "Vest"
grammar = "vest"
path_suffixes = ["vest"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "<", end = ">", close = true, newline = false },
]
word_characters = ["@"]
